### ISSUE TITLE
Case sensitivity require issue

### ISSUE THREAD

**Issue by dmfranko** [abeyahmad/servicenow-rest#3]
In the index.js the two below files are required with all lowercase, but the files are actually named GlideAggregate.js and GlideRecord.js.  When working on a case sensitive platform, such as Ubuntu 14.04.3 LTS, it's unable to find the required files. 

module.exports.gliderecord = require('./gliderecord.js');
module.exports.glideaggregate = require('./glideaggregate.js')

**Comment by abeyahmad** [comment]
This has been fixed.
